export const DATA_LOADING_BEGIN = "DATA_LOADING_BEGIN";
export const DATA_LOADING_SUCCEEDED = "DATA_LOADING_SUCCEEDED";
export const DATA_LOADING_FAILED = "DATA_LOADING_FAILED";

export const GET_TODAY_STATUS = "GET_TODAY_STATUS";
export const GET_TOTAL_STATUS = "GET_TOTAL_STATUS";
export const GET_REGION_LIST = "GET_REGION_LIST";
